services:
  # The Main Web Service (Django + Daphne)
  - type: web
    name: testDeployment
    autoDeploy: true
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT teams_chat.asgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DJANGO_SETTINGS_MODULE
        value: teams_chat.settings
      - key: DATABASE_URL
        value: postgresql://test1_clnq_user:8bPVw0BGZrQAEW8NKaqBm1LrfLOlSayA@dpg-d4phn2i4i8rc73fnqc0g-a/test1_clnq
