services:
  # The Main Web Service (Django + Daphne)
  - type: web
    name: testDeployment
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT teams_chat.asgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DJANGO_SETTINGS_MODULE
        value: teams_chat.settings
      - key: DATABASE_URL
        fromDatabase:
          name: testDeployment-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: testDeployment-db
    databaseName: test_deployment
    user: test_deployment_user
    plan: free
